apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: infra-challenge
type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: change-me
  MYSQL_DATABASE: infrachallenge
  MYSQL_USER: appuser
  MYSQL_PASSWORD: change-me