apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrachallenge-api
  namespace: infra-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infrachallenge-api

  template:
    metadata:
      labels:
        app: infrachallenge-api

    spec:
      containers:
        - name: infrachallenge-api
          image: nsonar/infrachallenge-api:1.0.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/infrachallenge

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"