apiVersion: v1
kind: Service
metadata:
  name: infrachallenge-service
  namespace: infra-challenge
spec:
  type: NodePort
  selector:
    app: infrachallenge-api

  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081